apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    app: nginx
    tier: frontend
spec:
  containers:
  - name: nginx
    image: nginx


# to create the POD using the above yanl file, use the below command
kubectl create -f pod-sample.yaml
        or 
kubectl apply -f pod-sample.yaml

# to get the status of the created pod, execute the belwo command
kubectl get pods -- this will give the status of the executed pod 

# to view the pod details, use the below command
kubectl describe pod <name-of-the-pod-created-above>
