apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
  
# Line 8 will be the considered as the major difference of the replicaset VS replicationcontroller, 
# selector --> this section helps the pod to match the type that is mentioned in the definition file and also helps to differentiate the previously created pods 
# from the one that is created using the replicaset definition file.

# to create the replicaset, use the below updated command.
kubectl create -f replicaset-definition-sample.yml

# to view the list of replicaset created, use the below updated command.
kubectl get replicaset 

# to view the pods created using the above replicaset definition file, use the below command.
kubectl get pods

# If you want to sclae up the pods using replicaset, then you need update the replicas value - to the desired number and execute the below command,
kubectl replace -f replicaset-definition-sample.yml

# the scale up can also be done using the below command,
kubectl scale --replicas=6 -f replicaset-definition-sample.yml
# Also you can run the below command if you desired to scale up the replicaset,
kubectl scale --replicaset=6 <kind-mentioned-inthe-defition-file> <name-underthe-metadata(first-value)>
kybectl scale --replicaset=6 replicaset myapp-replicaset
