apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    app: myapp


# to create the service, use the below command
kubectl create -f service-definition.yml

# to view the created service, use the blow command. with this command you can get the
  # port details through which u can access from outside the network
kubectl get services or kubectl get svc
# to find the URL to access, use the comamnd
minikube service myapp-service --url --> this only works when u working on the minikube 
